# Generated by Django 3.0.3 on 2020-04-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.CharField(default='admin', max_length=60)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(blank=True, upload_to='documents/')),
                ('document1', models.FileField(blank=True, upload_to='documents/')),
                ('document2', models.FileField(blank=True, upload_to='documents/')),
                ('training_status', models.BooleanField(default=False)),
                ('filetype', models.CharField(default='jpg', max_length=10)),
            ],
        ),
    ]
