# Generated by Django 3.0.5 on 2020-04-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='covidstate',
            field=models.CharField(blank=True, default='Not Processed', max_length=255),
        ),
    ]
