# Generated by Django 3.0.5 on 2020-04-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_document_covidstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
