# Generated by Django 3.0.5 on 2020-04-14 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0003_document_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='update',
            new_name='updated',
        ),
    ]
