# Generated by Django 3.0.5 on 2020-04-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0005_document_predictstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, upload_to='fileupload/uploads/'),
        ),
    ]
